version: '3.3'

networks:
  warper-network:
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/aklaikel/data/wp
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device:  /home/aklaikel/data/db
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/Mariadb
    env_file:
      - .env
    networks:
      - warper-network
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    build: ./requirements/WordPress
    networks:
      - warper-network
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    restart: unless-stopped
  
  nginx:
    container_name: Nginx
    build: ./requirements/Nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - warper-network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: unless-stopped
  site:
    container_name: site
    build: ./bonus/site
    ports:
      - "5000:5000"
    networks:
      - warper-network
    env_file:
      - .env
    restart: unless-stopped
  ftp_server:
    container_name: ftp-server
    build: ./bonus/ftp-server
    volumes:
      - wp:/home/"
    ports:
      - "21:21"
      - "20:20"
      - "21000-21010:21000-21010"
    networks:
      - warper-network
    env_file:
      - .env
    restart: unless-stopped
  adminer:
    container_name: adminer
    build: ./bonus/adminer
    ports:
      - "1337:1337"
    networks:
      - warper-network
    depends_on:
      - mariadb
    restart: always
  redis:
    container_name: redis
    build: ./bonus/redis
    ports:
      - "6379:6379"
    networks:
      - warper-network
    depends_on:
      - wordpress
    restart: always
  cadvisor: 
    container_name: cadvisor
    build: ./bonus/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "2000:2000"
    networks:
      - warper-network
    restart: always
  